version: "3"

services:
  auth:
    image: apiauthtrafficai
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  ai:
    image: aitrafficai
    build:
      context: ./backend/AIapi
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: